version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    image: app:myappimage16.14.2.alpine
    container_name: myapp
    command: npm start
