version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./DockerfileNginx
    volumes:
      - .:/app
    ports:
      - 3000:80
    image: app:myappimage16.14.2.alpine
    container_name: myapp
